# Generated by Django 3.0.2 on 2020-01-23 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0002_auto_20200115_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='slug',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=models.TextField(default=''),
        ),
    ]
