# Generated by Django 3.0.2 on 2020-01-23 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0003_auto_20200123_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='slug',
            field=models.CharField(default='', max_length=500),
        ),
    ]
