# Generated by Django 3.0.2 on 2020-01-23 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0004_auto_20200123_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
