# Generated by Django 3.0.2 on 2020-01-23 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0006_auto_20200123_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='category',
        ),
        migrations.DeleteModel(
            name='QuestionCategory',
        ),
    ]
